### ISSUE TITLE
BabelSememe Dataset missing

### ISSUE THREAD

**Issue by pasinit** [thunlp/BabelNet-Sememe-Prediction#1]
Dears, 
thanks for sharing the code and the data. However, I noticed that the file ./BabelSememe/synset_sememes.txt is missing from the repo.

Would it be possible for you to upload it?

Thanks, 
Tommaso

**Comment by clpl** [comment]
Sorry, something went wrong while uploading the file. Thank you for pointing out the mistake.

We just uploaded ./BabelSememe/synset_sememes.txt to the repository.

**Comment by pasinit** [comment]
thank you so much!
