### ISSUE TITLE
what does strings e.g., "bn:00113968a" mean? 

### ISSUE THREAD

**Issue by jingliao132** [thunlp/BabelNet-Sememe-Prediction#2]
When I check the file of synset_sememes.txt, I am curious about the strings in the first column. How are they produced?

**Comment by clpl** [comment]
Like WordNet ID, for example: "wn: 00001930n". BabelNet also numbers its synsets. "bn" stands for BabelNet. "00113968" is the ID, and "a" means this synset is an adjective. The rule is bn: (synset offset) (POS of synset). You can visit [babelnet.org](https://babelnet.org/) to learn about BabelNet synset.

**Comment by jingliao132** [comment]
Thanks for your clear reply and contributions to open source data. I just encountered another problem when running "python ./SPBS-SR/EvalSememePre_SPWE.py". The prompts is that there is no "data-noun/test.txt" and "data-noun/train.txt", but the script defines such files as inputs (at line 115, 149-150). 

May I know how did you generate "data-noun/train.txt" and "data-noun/test.txt"?

**Comment by clpl** [comment]
I just uploaded these files, "\*id.txt" is obtained by converting entity and relation of "*.txt" to id using "entity2id.txt" and "relation2id.txt". The conversion method can be found at [OpenKE#data](https://github.com/thunlp/OpenKE#data).
