### ISSUE TITLE
About BabelNet entities

### ISSUE THREAD

**Issue by HuuuNan** [thunlp/BabelNet-Sememe-Prediction#3]
Thanks for sharing the code and the data!
I notice that there are 15756 BabelNet entities (start with bn:xxxx) in the file synset_sememes.txt, they look like not all the BabelNet entities. Do you use any method to filter these entities?

**Comment by clpl** [comment]
Thanks for your issue! 
We select the "key" synsets as the seed dataset. The "key" measurement has several aspects, such as
* Whether it is connected to wordnet.
* The number of languages in the synset.
* The number of edges connected to the synset in the Babelnet semantic network.

We considered the three factors to calculate the scores, sort them, and select the synset with high scores.

**Comment by HuuuNan** [comment]
@clpl Thanks a lot for your reply!
